const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),stage=canvas.parentElement,burn=document.querySelector('#burn'),result=document.querySelector('#result'),resultTitle=document.querySelector('#resultTitle'),resultKicker=document.querySelector('#resultKicker');let W=0,H=0,dpr=1,last=0,state='play',burning=false,sound=false,attempt=1,cloudTop=0,cloudBottom=0,gap=0;const balloon={x:0,y:0,vy:0,r:0};const particles=[];
function resize(){const r=stage.getBoundingClientRect();W=r.width;H=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);newRound(false)}
new ResizeObserver(resize).observe(stage);
function newRound(count=true){if(count)attempt++;document.querySelector('#attempt').textContent=String(attempt).padStart(2,'0')+' / UN INTENTO';state='play';burning=false;result.hidden=true;particles.length=0;balloon.r=Math.max(17,Math.min(24,W*.045));balloon.x=W*.15;balloon.y=H*(.46+(Math.random()-.5)*.12);balloon.vy=0;gap=Math.max(balloon.r*2.7,H*.18)*1.10;const minCenter=gap/2+H*.12,maxCenter=H*.68-gap/2;const center=minCenter+Math.random()*(maxCenter-minCenter);cloudTop=center-gap/2;cloudBottom=center+gap/2}
function cloud(x,y,w,h){ctx.save();ctx.fillStyle='#c8c8c2';ctx.shadowColor='#78908a33';ctx.shadowBlur=12;ctx.beginPath();ctx.ellipse(x,y,w*.28,h*.35,0,0,Math.PI*2);ctx.ellipse(x+w*.24,y-h*.12,w*.25,h*.42,0,0,Math.PI*2);ctx.ellipse(x+w*.48,y,w*.34,h*.48,0,0,Math.PI*2);ctx.ellipse(x+w*.72,y-h*.08,w*.26,h*.4,0,0,Math.PI*2);ctx.ellipse(x+w*.9,y,w*.25,h*.34,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawBalloon(){const r=balloon.r;ctx.save();ctx.translate(balloon.x,balloon.y);ctx.shadowColor='#173f3e26';ctx.shadowBlur=7;const g=ctx.createLinearGradient(-r,0,r,0);g.addColorStop(0,'#9e493b');g.addColorStop(.28,'#d77b55');g.addColorStop(.5,'#f1b06f');g.addColorStop(.72,'#d77b55');g.addColorStop(1,'#914238');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,-r*1.32);ctx.bezierCurveTo(r*.82,-r*1.2,r*.94,-r*.25,r*.55,r*.45);ctx.bezierCurveTo(r*.34,r*.82,r*.16,r*.88,0,r*.92);ctx.bezierCurveTo(-r*.16,r*.88,-r*.34,r*.82,-r*.55,r*.45);ctx.bezierCurveTo(-r*.94,-r*.25,-r*.82,-r*1.2,0,-r*1.32);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#f4c895';ctx.lineWidth=1.2;for(const q of[-.38,0,.38]){ctx.beginPath();ctx.moveTo(q*r,-r*1.2);ctx.quadraticCurveTo(q*r*.45,-r*.15,q*r*.55,r*.72);ctx.stroke()}ctx.fillStyle='#6d4634';ctx.fillRect(-r*.18,r*.83,r*.36,r*.12);ctx.strokeStyle='#6d4634';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-r*.28,r*.62);ctx.lineTo(-r*.34,r*1.05);ctx.moveTo(r*.28,r*.62);ctx.lineTo(r*.34,r*1.05);ctx.stroke();ctx.fillStyle='#9a6847';ctx.fillRect(-r*.38,r*1.02,r*.76,r*.38);ctx.strokeStyle='#6d4634';ctx.strokeRect(-r*.38,r*1.02,r*.76,r*.38);if(burning&&state==='play'){ctx.fillStyle='#ef762f';ctx.beginPath();ctx.moveTo(-r*.15,r*.8);ctx.quadraticCurveTo(0,r*1.35,r*.15,r*.8);ctx.fill();ctx.fillStyle='#ffd76a';ctx.beginPath();ctx.moveTo(-r*.065,r*.82);ctx.quadraticCurveTo(0,r*1.16,r*.065,r*.82);ctx.fill()}ctx.restore()}
function scenery(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#e8f0e9');sky.addColorStop(.7,'#f6f1e5');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ead7a7';ctx.globalAlpha=.65;ctx.beginPath();ctx.arc(W*.8,H*.16,H*.065,0,7);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#d5e1d9';ctx.beginPath();ctx.moveTo(0,H*.78);ctx.lineTo(W*.27,H*.7);ctx.lineTo(W*.55,H*.78);ctx.lineTo(W*.82,H*.68);ctx.lineTo(W,H*.73);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.fillStyle='#bfd2c7';ctx.beginPath();ctx.moveTo(0,H*.88);ctx.lineTo(W*.35,H*.78);ctx.lineTo(W*.68,H*.86);ctx.lineTo(W,H*.79);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();const cx=W*.70,cw=W*.38,ch=H*.20;cloud(cx,cloudTop-ch*.3,cw,ch);cloud(cx,cloudBottom+ch*.3,cw,ch)}
function collide(){const cx=W*.70,cw=W*.38,ch=H*.20;const bx=balloon.x,by=balloon.y-rad(),rr=balloon.r*.66;if(bx+rr<cx-cw*.28||bx-rr>cx+cw*1.16)return false;return by-rr<cloudTop||by+rr>cloudBottom}function rad(){return balloon.r*.35}
function strike(){if(state!=='play')return;state='struck';burning=false;beep(90,.18);setTimeout(()=>state='fall',160)}
function success(){if(state!=='play')return;state='success';burning=false;for(let i=0;i<55;i++)particles.push({x:balloon.x,y:balloon.y,vx:(Math.random()-.5)*220,vy:-Math.random()*230-40,g:320,s:2+Math.random()*4,a:Math.random()*6.28});beep(660,.08);setTimeout(()=>showResult(true),550)}
function showResult(ok){state='result';resultKicker.textContent=ok?'PASASTE LIMPIO':'TE ALCANZÓ EL RAYO';resultTitle.textContent=ok?'PERFECTO.':'CASI.';result.hidden=false;window.goatcounter?.count?.({path:'partida-completada',title:ok?'El Hueco - exito':'El Hueco - fallo',event:true})}
function update(dt){if(state==='play'){balloon.x+=W*.105*dt;balloon.vy+=(burning?-H*.62:H*.20)*dt;balloon.vy=Math.max(-H*.19,Math.min(H*.16,balloon.vy));balloon.y+=balloon.vy*dt;if(collide())strike();else if(balloon.x-balloon.r>W*.96)success();if(balloon.y>H*.92||balloon.y<balloon.r*1.2)strike()}else if(state==='fall'){balloon.vy+=H*.9*dt;balloon.y+=balloon.vy*dt;if(balloon.y>H*.9){balloon.y=H*.9;showResult(false)}}for(const p of particles){p.vy+=p.g*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.a+=dt*4}}
function drawLightning(){if(state!=='struck'&&state!=='fall')return;const topY=Math.max(4,balloon.y-H*.28),endY=balloon.y+balloon.r*.45;const pts=[[balloon.x+12,topY],[balloon.x-5,topY+H*.07],[balloon.x+10,topY+H*.105],[balloon.x-12,topY+H*.17],[balloon.x+3,topY+H*.195],[balloon.x-2,endY]];ctx.save();ctx.lineJoin='miter';ctx.lineCap='butt';ctx.shadowColor='#fff3a0';ctx.shadowBlur=13;ctx.strokeStyle='#fff7c2';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(...pts[0]);for(let i=1;i<pts.length;i++)ctx.lineTo(...pts[i]);ctx.stroke();ctx.shadowBlur=5;ctx.strokeStyle='#f2b51d';ctx.lineWidth=4;ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=1.3;ctx.stroke();ctx.restore()}
function drawParticles(){ctx.fillStyle='#b85d43';for(const p of particles){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.a);ctx.fillRect(-p.s,-p.s/2,p.s*2,p.s);ctx.restore()}}
function frame(t){const dt=Math.min((t-last)/1000||0,.03);last=t;update(dt);scenery();drawLightning();drawBalloon();drawParticles();requestAnimationFrame(frame)}requestAnimationFrame(frame);
function setBurn(v){if(state!=='play')return;burning=v;burn.classList.toggle('on',v);if(v)beep(190,.035)}['pointerdown','touchstart'].forEach(e=>burn.addEventListener(e,ev=>{ev.preventDefault();setBurn(true)},{passive:false}));['pointerup','pointercancel','pointerleave','touchend'].forEach(e=>burn.addEventListener(e,ev=>{ev.preventDefault();setBurn(false)},{passive:false}));document.querySelector('#again').onclick=()=>newRound(true);
document.querySelector('#sound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'🔊':'🔇';if(sound)beep(440,.04)};function beep(f,d){if(!sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=beep.a||(beep.a=new A),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g).connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+d);o.stop(a.currentTime+d)}
const fd=document.querySelector('#favDialog');document.querySelector('#favorite').onclick=()=>fd.showModal();document.querySelector('#closeFav').onclick=()=>fd.close();