const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),stage=canvas.parentElement,burn=document.querySelector('#burn'),ready=document.querySelector('#ready'),result=document.querySelector('#result'),resultTitle=document.querySelector('#resultTitle'),resultKicker=document.querySelector('#resultKicker');let W=0,H=0,dpr=1,last=0,state='play',burning=false,sound=false,attempt=1,cloudTop=0,cloudBottom=0,gap=0;const balloon={x:0,y:0,vy:0,r:0};const particles=[];
function resize(){const r=stage.getBoundingClientRect();W=r.width;H=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);newRound(false)}
new ResizeObserver(resize).observe(stage);
function newRound(count=true){if(count)attempt++;document.querySelector('#attempt').textContent=String(attempt).padStart(2,'0')+' / UN INTENTO';state='play';burning=false;result.hidden=true;ready.hidden=false;particles.length=0;balloon.r=Math.max(17,Math.min(24,W*.045));balloon.x=W*.15;balloon.y=H*(.46+(Math.random()-.5)*.12);balloon.vy=0;gap=Math.max(balloon.r*2.7,H*.18);const center=H*(.43+(Math.random()-.5)*.16);cloudTop=center-gap/2;cloudBottom=center+gap/2}
function cloud(x,y,w,h){ctx.save();ctx.fillStyle='#f8f8f1';ctx.shadowColor='#78908a33';ctx.shadowBlur=12;ctx.beginPath();ctx.ellipse(x,y,w*.28,h*.35,0,0,Math.PI*2);ctx.ellipse(x+w*.24,y-h*.12,w*.25,h*.42,0,0,Math.PI*2);ctx.ellipse(x+w*.48,y,w*.34,h*.48,0,0,Math.PI*2);ctx.ellipse(x+w*.72,y-h*.08,w*.26,h*.4,0,0,Math.PI*2);ctx.ellipse(x+w*.9,y,w*.25,h*.34,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawBalloon(){const r=balloon.r;ctx.save();ctx.translate(balloon.x,balloon.y);ctx.fillStyle='#c36b4c';ctx.beginPath();ctx.ellipse(0,-r*.35,r*.72,r,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f0c18f';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(-r*.3,-r*1.05);ctx.quadraticCurveTo(0,-r*.35,-r*.2,r*.5);ctx.moveTo(r*.3,-r*1.05);ctx.quadraticCurveTo(0,-r*.35,r*.2,r*.5);ctx.stroke();ctx.strokeStyle='#765344';ctx.beginPath();ctx.moveTo(-r*.22,r*.42);ctx.lineTo(-r*.28,r*.82);ctx.moveTo(r*.22,r*.42);ctx.lineTo(r*.28,r*.82);ctx.stroke();ctx.fillStyle='#9b6a48';ctx.fillRect(-r*.32,r*.78,r*.64,r*.35);if(burning&&state==='play'){ctx.fillStyle='#f4a21d';ctx.beginPath();ctx.moveTo(-r*.14,r*.5);ctx.quadraticCurveTo(0,r*1.08,r*.14,r*.5);ctx.fill();ctx.fillStyle='#fff1a5';ctx.beginPath();ctx.moveTo(-r*.06,r*.52);ctx.quadraticCurveTo(0,r*.88,r*.06,r*.52);ctx.fill()}ctx.restore()}
function scenery(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#e8f0e9');sky.addColorStop(.7,'#f6f1e5');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ead7a7';ctx.globalAlpha=.65;ctx.beginPath();ctx.arc(W*.8,H*.16,H*.065,0,7);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#d5e1d9';ctx.beginPath();ctx.moveTo(0,H*.78);ctx.lineTo(W*.27,H*.7);ctx.lineTo(W*.55,H*.78);ctx.lineTo(W*.82,H*.68);ctx.lineTo(W,H*.73);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.fillStyle='#bfd2c7';ctx.beginPath();ctx.moveTo(0,H*.88);ctx.lineTo(W*.35,H*.78);ctx.lineTo(W*.68,H*.86);ctx.lineTo(W,H*.79);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();const cx=W*.70,cw=W*.38,ch=H*.20;cloud(cx,cloudTop-ch*.3,cw,ch);cloud(cx,cloudBottom+ch*.3,cw,ch)}
function collide(){const cx=W*.70,cw=W*.38,ch=H*.20;const bx=balloon.x,by=balloon.y-rad(),rr=balloon.r*.66;if(bx+rr<cx-cw*.28||bx-rr>cx+cw*1.16)return false;return by-rr<cloudTop||by+rr>cloudBottom}function rad(){return balloon.r*.35}
function strike(){if(state!=='play')return;state='struck';burning=false;ready.hidden=true;beep(90,.18);setTimeout(()=>state='fall',160)}
function success(){if(state!=='play')return;state='success';burning=false;ready.hidden=true;for(let i=0;i<55;i++)particles.push({x:balloon.x,y:balloon.y,vx:(Math.random()-.5)*220,vy:-Math.random()*230-40,g:320,s:2+Math.random()*4,a:Math.random()*6.28});beep(660,.08);setTimeout(()=>showResult(true),550)}
function showResult(ok){state='result';resultKicker.textContent=ok?'PASASTE LIMPIO':'TE ALCANZÓ EL RAYO';resultTitle.textContent=ok?'PERFECTO.':'CASI.';result.hidden=false;window.goatcounter?.count?.({path:'partida-completada',title:ok?'El Hueco - exito':'El Hueco - fallo',event:true})}
function update(dt){if(state==='play'){balloon.x+=W*.105*dt;balloon.vy+=(burning?-H*.62:H*.20)*dt;balloon.vy=Math.max(-H*.19,Math.min(H*.16,balloon.vy));balloon.y+=balloon.vy*dt;if(collide())strike();else if(balloon.x-balloon.r>W*.96)success();if(balloon.y>H*.92||balloon.y<balloon.r*1.2)strike()}else if(state==='fall'){balloon.vy+=H*.9*dt;balloon.y+=balloon.vy*dt;if(balloon.y>H*.9){balloon.y=H*.9;showResult(false)}}for(const p of particles){p.vy+=p.g*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.a+=dt*4}}
function drawLightning(){if(state!=='struck'&&state!=='fall')return;ctx.strokeStyle='#f2b31b';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(balloon.x-18,balloon.y-H*.16);ctx.lineTo(balloon.x+5,balloon.y-H*.09);ctx.lineTo(balloon.x-7,balloon.y-H*.04);ctx.lineTo(balloon.x+8,balloon.y);ctx.stroke()}
function drawParticles(){ctx.fillStyle='#b85d43';for(const p of particles){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.a);ctx.fillRect(-p.s,-p.s/2,p.s*2,p.s);ctx.restore()}}
function frame(t){const dt=Math.min((t-last)/1000||0,.03);last=t;update(dt);scenery();drawLightning();drawBalloon();drawParticles();requestAnimationFrame(frame)}requestAnimationFrame(frame);
function setBurn(v){if(state!=='play')return;burning=v;burn.classList.toggle('on',v);if(v)beep(190,.035)}['pointerdown','touchstart'].forEach(e=>burn.addEventListener(e,ev=>{ev.preventDefault();setBurn(true)},{passive:false}));['pointerup','pointercancel','pointerleave','touchend'].forEach(e=>burn.addEventListener(e,ev=>{ev.preventDefault();setBurn(false)},{passive:false}));document.querySelector('#again').onclick=()=>newRound(true);
document.querySelector('#sound').onclick=e=>{sound=!sound;e.currentTarget.textContent=sound?'🔊':'🔇';if(sound)beep(440,.04)};function beep(f,d){if(!sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=beep.a||(beep.a=new A),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g).connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+d);o.stop(a.currentTime+d)}
const fd=document.querySelector('#favDialog');document.querySelector('#favorite').onclick=()=>fd.showModal();document.querySelector('#closeFav').onclick=()=>fd.close();